trigger:
  branches:
    include:
      - main
      
pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'
variables:
- name: sonarCloudEndpointName 
  value: 'sonarcloud_service_connection'
- name: sonarCloudProjectName 
  value: 'Demo Project'
- group: Code_Fix_Agent_dotenv
- name: PYTHON_VERSION
  value: '3.10'
resources:
  repositories:
    - repository: self
    - repository: sonarqube-issue-fixer
      type: git
      name: "SonarQube Issue Fixer/SonarQube Issue Fixer"

steps:
- checkout: self

- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: '$(sonarCloudEndpointName)'
    organization: '$(SONAR_ORGANISATION)'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(SONAR_PROJECT_KEY)'
    cliProjectName: '$(sonarCloudProjectName)'
    cliProjectVersion: '1.0'
    cliSources: '.'

- task: SonarCloudAnalyze@2

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'
- checkout: sonarqube-issue-fixer

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    addToPath: true

- task: Cache@2
  inputs:
    key: 'python | "$(Agent.OS)" | "$(PYTHON_VERSION)" | $(Build.SourcesDirectory)/SonarQube Issue Fixer/sonarqube-project/scripts/requirements.txt'
    restoreKeys: |
      python | "$(Agent.OS)" | "$(PYTHON_VERSION)"
      python | "$(Agent.OS)"
      python
    path: $(Pipeline.Workspace)/venv
- script: |
    python -m venv $(Pipeline.Workspace)/venv
    source $(Pipeline.Workspace)/venv/bin/activate
    python -m pip install --upgrade pip
    pip install -r '$(Build.SourcesDirectory)/SonarQube Issue Fixer/sonarqube-project/scripts/requirements.txt'
  displayName: 'Setup Python venv'
  condition: ne(variables['CacheRestored'], 'true')
- script: |
    source $(Pipeline.Workspace)/venv/bin/activate
    echo "Python version:"
    python --version
    echo "Pip version:"
    pip --version
  displayName: 'Verify Python Environment'

# Run Python script to retrieve SonarCloud issues
- script: |
    source $(Pipeline.Workspace)/venv/bin/activate
    python '$(Build.SourcesDirectory)/SonarQube Issue Fixer/sonarqube-project/sonar_issues/fetch_sonarcloud_issues.py' $(SONAR_ORGANISATION) $(SONAR_PROJECT_KEY) $(SONAR_TOKEN)
  displayName: 'Retrieve SonarCloud Issues'
  workingDirectory: '$(Build.SourcesDirectory)/SonarQube Issue Fixer/sonarqube-project'

# Publish issues as an artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/SonarQube Issue Fixer/sonarqube-project/issues.json'
    artifactName: 'SonarCloudIssues'
    publishLocation: 'pipeline'

# Run fixer_agent.py script using issues.json as input
- script: |
    source $(Pipeline.Workspace)/venv/bin/activate
    python backend/services/sonar_qube_fixer_agent/src/fixer_agent.py 'issues.json'
  displayName: 'Run Fixer Agent Script'
  workingDirectory: '$(Build.SourcesDirectory)/SonarQube Issue Fixer/sonarqube-project'
  env:
    CURRENT_BRANCH: $(CURRENT_BRANCH)
    GITHUB_ACCESS_TOKEN: $(GITHUB_ACCESS_TOKEN)
    OPENAI_API_KEY: $(OPENAI_API_KEY)
    OPENAI_MODEL: $(OPENAI_MODEL)
    REPO_URL: $(REPO_URL)