trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  sonarCloudEndpointName: 'sonarcloud_service_connection'
  sonarCloudOrganization: 'kireplyuk'
  sonarCloudProjectKey: 'kireplyuk_test-project'
  sonarCloudProjectName: 'Test Project'
  sonarCloudToken: '7b5c07aaab9d7781d6f8674a1f8a62b743d42413'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: '$(sonarCloudEndpointName)'
    organization: '$(sonarCloudOrganization)'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(sonarCloudProjectKey)'
    cliProjectName: '$(sonarCloudProjectName)'
    cliProjectVersion: '1.0'
    cliSources: '.'  # Update this to the correct source directory

# Add your build task(s) here
- script: |
    echo "Building the project..."
    # Replace this with your actual build command, for example:
    # dotnet build, mvn clean install, etc.
    # Here, it's assumed that the build script is a simple echo command for illustration.
  displayName: 'Build the project'

- task: SonarCloudAnalyze@1

# Uncomment the next task to wait until SonarCloud processing has finished and to publish the result on the Pipeline build summary
#- task: SonarCloudPublish@1
#  inputs:
#    pollingTimeoutSec: '300'
