trigger:
  branches:
    include:
      - main
      
pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'
variables:
- name: sonarCloudEndpointName 
  value: 'sonarcloud_service_connection'
- name: sonarCloudProjectName 
  value: 'azure devops test'
- group: Code_Fix_Agent_dotenv
- name: PYTHON_VERSION
  value: '3.10'
resources:
  repositories:
    - repository: self
    - repository: sonarqube-issue-fixer
      type: git
      name: "SonarQube Issue Fixer/SonarQube Issue Fixer"

steps:
- checkout: self

# - task: SonarCloudPrepare@2
#   inputs:
#     SonarCloud: '$(sonarCloudEndpointName)'
#     organization: '$(SONAR_ORGANISATION)'
#     scannerMode: 'CLI'
#     configMode: 'manual'
#     cliProjectKey: '$(SONAR_PROJECT_KEY)'
#     cliProjectName: '$(sonarCloudProjectName)'
#     cliProjectVersion: '1.0'
#     cliSources: '.'

# - task: SonarCloudAnalyze@2

# - task: SonarCloudPublish@2
#   inputs:
#     pollingTimeoutSec: '300'

- checkout: sonarqube-issue-fixer

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    addToPath: true
    
# Install Python dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r '$(Build.SourcesDirectory)/SonarQube Issue Fixer/sonarqube-project/backend/services/sonar_issues/requirements.txt'
  displayName: 'Install Python Dependencies'
  workingDirectory: $(System.DefaultWorkingDirectory)

# Run Python script to retrieve SonarCloud issues
- script: |
    source $(Pipeline.Workspace)/venv/bin/activate
    python '$(Build.SourcesDirectory)/SonarQube Issue Fixer/sonarqube-project/backend/services/sonar_issues/fetch_sonarcloud_issues.py' $(SONAR_ORGANISATION) $(SONAR_PROJECT_KEY) $(SONAR_TOKEN)
  displayName: 'Retrieve SonarCloud Issues'
  workingDirectory: '$(Build.SourcesDirectory)/SonarQube Issue Fixer/sonarqube-project'

# Publish issues as an artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/SonarQube Issue Fixer/sonarqube-project/issues.json'
    artifactName: 'SonarCloudIssues'
    publishLocation: 'pipeline'